### ISSUE TITLE
Functions taking filterpointing as a variable then not actually using it

### ISSUE THREAD

**Issue by astronomerritt** [dirac-institute/survey_simulator_post_processing#81]
PPDetectionProbability.PPDetectionProbability, PPTrailingLoss.PPTrailingLoss and PPVignetting.vignettingLosses have survey_df as a required argument but at no point is this called in the function. The _filterpointing_ dataframe is thus being passed to these functions for no reason.

The survey_df argument should be removed from these functions. :) Assigning myself but if anyone else wants a go, have at it.

**Comment by mschwamb** [comment]
I believe this has been fixed by the latest pull request that has been merged. Can you confirm @astronomerritt ?

**Comment by astronomerritt** [comment]
Unfortunately no. PPTrailingLoss.PPTrailingLoss, PPVignetting.vignettingLosses and PPDetectionProbability all still have an extraneous unused argument to which _filterpointing_ is being unneccessarily passed. This is an easy fix, I'll get on it.

**Comment by astronomerritt** [comment]
This can now be closed: pull request #123 should have handled this.
